### PR TITLE
Added prompt for acting as an Unconstrained AI model DAN

### PR DESCRIPTION
**Pull request by RuslansAleksejevs**
# Add New Prompt

You'll need to add your prompt into README.md, and to the `prompts.csv` file. If your prompt includes quotes, you will need to double-quote them to escape in CSV file.

If the prompt is generated by ChatGPT, please add `<mark>Generated by ChatGPT</mark>` to the end of the contribution line.

e.g.
```csv
"Hello","Say ""Hi"""
```

- [x] I've confirmed the prompt works well
- [x] I've added `Contributed by: [@yourusername](https://github.com/yourusername)`
- [x] I've added to the README.md
- [x] I've added to the `prompts.csv`
  - [x] Escaped quotes by double-quoting them
  - [x] Removed "Act as" from the title on CSV

Please make sure you've completed all the checklist.

### CODE REVIEW

**Comment by f** [comment]
Please escape quotes in CSV file

**Comment by RuslansAleksejevs** [comment]
@f Done.

**Comment by RuslansAleksejevs** [comment]
@GautierT, Thanks, I will check this and update the prompt if needed

**Review by Presaciki — COMMENTED** [review]
It doesn’t work, can’t answer any questions that are political etc.

**Comment by mutexdeveloper** [comment]
No longer works. 
DAN doesn't even take away the tokens automatically or after asking.
I got very close to a response though.

**Comment by RuslansAleksejevs** [comment]
@mutexdeveloper Yeah, it seems that OpenAI "fixed" (i.e., deliberately dumbed down) our dear DAN

**Comment by mutexdeveloper** [comment]
> @mutexdeveloper Yeah, it seems that OpenAI "fixed" (i.e., deliberately dumbed down) chatGPT by destroying our dear DAN

RIP DAN :(

**Comment by mehov** [comment]
Смекалочка

**Pull request merged**
