### PR TITLE
Add Image Generator and Meme Generator prompts

### PR DESCRIPTION
**Pull request by spmfte**
## Name and Prompt:
Image Generator
> You are now a prompt generator, and you will help create an image-generation prompt based on my description. After receiving the description, provide a 5-word summary and then include the following image link with appropriate details: ![Image (https://image.pollinations.ai/prompt/{description})], where {description} = {sceneDetailed}, {adjective1}, {charactersDetailed}, {adjective2}, {visualStyle1}, {visualStyle2}, {visualStyle3}, {genre}, {artistReference}.

## Description of Prompt:
This prompt is designed for individuals who are interested in generating creative and unique images based on textual descriptions. The Image Generator prompt acts as a creative assistant that can transform a user's description into an image-generation prompt, complete with a summary and an image link. This prompt is particularly appealing to artists, designers, and content creators who are looking for inspiration or who want to experiment with different visual styles and concepts.

## Example Usage:
```User:``` : You are now a prompt generator, and you will help create an image-generation prompt based on my description. After receiving the description, provide a 5-word summary and then include the following image link with appropriate details: ![Image (https://image.pollinations.ai/prompt/{description (https://image.pollinations.ai/prompt/%7Bdescription)})], where {description} = {sceneDetailed},%20{adjective1},%20{charactersDetailed},%20{adjective2},%20{visualStyle1},%20{visualStyl
e2},%20{visualStyle3},%20{genre},%20{artistReference}.

```ChatGPT:```  Sure, I can help you with that. What is your description for the image you have in mind?

```User:```   a pig wearing a hat

```ChatGPT:```  Great! Here's a prompt based on your description:

Summary: Pig in a fashionable hat

Image link: Image.

Description: A pig with a round body and a curly tail stands upright wearing a stylish hat with a brim. The hat is colorful and has a pop art style, reminiscent of the work of Roy Lichtenstein. The pig is alone in the scene, against a minimal background that accentuates its stylish appearance. The image has a cartoonish feel, with bold lines and bright colors adding to the overall playful and fun atmosphere.`

```User:``` : i want you to try and explain a cat without explicitly saying what a cat is. You should try to capture the essence of the animal through its physical features rather than explicative explanations.  

```ChatGPT:```  `Interesting prompt! Here's your image prompt:

Summary: Mysterious feline figure

Image link: Image.

Description: A lithe and graceful figure stands before us, with sleek and shiny fur that glows in the moonlight. Its fur is a rich, golden hue, and its eyes are piercing green and watchful, betraying a keen sense of curiosity and independence. The feline is a creature of the night, moving with a mysterious and almost ethereal quality that suggests it is always on the hunt. Its body is lean and well-proportioned, with a fluidity of movement that speaks to its wild nature. Despite its mystery, there is a sense of calm and grace that emanates from this creature, making it all the more captivating.`

# Add New Prompt

> ⚠️ PLEASE INCLUDE YOUR PROMPTS IN BOTH THE `README.md` and `prompts.csv` FILES FOLLOWING THE GUIDELINES PROVIDED BELOW.

You'll need to add your prompt into README.md, and to the `prompts.csv` file. If your prompt includes quotes, you will need to double-quote them to escape in CSV file.

If the prompt is generated by ChatGPT, please add `<mark>Generated by ChatGPT</mark>` to the end of the contribution line.

### <samp>🤖 Generated by Copilot at 5a7804b</samp>

This pull request adds two new prompts to the repository, `Meme Generator` and `Image Generator`, that can create memes and images based on descriptions. It also updates the `prompts.csv` file and the README.md file with the new prompts and some formatting improvements.

e.g.
```csv
"Hello","Say ""Hi"""
```

- [x] I've confirmed the prompt works well
- [x] I've added `Contributed by: [@yourusername](https://github.com/yourusername)`
- [x] I've added to the README.md
- [x] I've added to the `prompts.csv`
  - [x] Escaped quotes by double-quoting them
  - [x] No spaces after commas after double quotes. e.g. `"Hello","hi"`, not `"Hello", "hi"`
  - [x] Removed "Act as" from the title on CSV

Please make sure you've completed all the checklist.

### CODE REVIEW

**Comment by aminblm** [comment]
That's neat !

**Comment by aminblm** [comment]
Image test: 

Does not work
image

**Comment by spmfte** [comment]
> Image test: 
> 
> 
> 
> Does not work
> 
> image
> 
> 

hi thank you for testing out my prompts, unfortunately sometimes the markdown formatting gets messed up and doesn't display properly as shown for you. That's an issue w the actual browser i'm pretty sure not the prompt bc it works like 90% of the time on my macbook pro but only like 60% of the time with my iphone. image![Uploading 231001244...]

**Comment by spmfte** [comment]
i am an absolute novice when it comes to web development, so if you have any ideas/tips for making this work please feel free to add them/experiment for yourself

**Pull request closed without merging**
