### PR TITLE
Sponsorship

### PR DESCRIPTION
**Pull request by sergey-shpak**

### CODE REVIEW

**Comment by sergey-shpak** [comment]
@f ?

**Comment by f** [comment]
Hey, the sponsorship doesn't work that way. Why did you think so?

**Comment by sergey-shpak** [comment]
@f I might be missing something, but for sponsorship tier I subscribed it is saying `Logo or name goes in my project README`

**Comment by sergey-shpak** [comment]
> @f I might be missing something, but for sponsorship tier I subscribed it is saying `Logo or name goes in my project README`

@f any updates?

**Comment by sergey-shpak** [comment]
@f updated sponsorship and made it public(previously it was private 😉)

**Pull request closed without merging**
