### PR TITLE
Remove foolishness

### PR DESCRIPTION
**Pull request by yisraeldov**
This has no place in a FOSS project.

### CODE REVIEW

**Comment by yisraeldov** [comment]
yep

**Review by victorabarros — APPROVED** [review]

**Comment by unix14** [comment]
Free Israel from Iran
Palestine is free - and still nobody wants it.

**Comment by unix14** [comment]
Free Plastelina from Hamas

**Comment by maxhr** [comment]
Please report to GitHub the owner of this repo - https://support.github.com/contact/report-abuse?category=report-abuse

**Comment by yisraeldov** [comment]
@victorabarros Can you reopen this PR, it was closed with no feed back and all the comments were deleted.

**Comment by yisraeldov** [comment]
@maxhr @unix14 @alien2003 @brainjm @weinbergdavid, @BrianJM, @3top1a,  @R-Dson, @victorwolff39, @przvlprd, victorabarros, @aserper @vwit, @raccoonex, @karllos50, @vpopovec, @Narry1337, @Dimanssional, @vkislichenko

Sorry for the spam, this PR was closed with no reasons given and all comments were deleted. Maybe you can open your own pr with the same patch.

**Pull request closed without merging**
