### PR TITLE
Fix restaurant owner prompt

### PR DESCRIPTION
**Pull request by casch-at**
To get "..." we need to quote the quoted string like ""...""

# Add New Prompt

> ⚠️ PLEASE INCLUDE YOUR PROMPTS IN BOTH THE `README.md` and `prompts.csv` FILES FOLLOWING THE GUIDELINES PROVIDED BELOW.

You'll need to add your prompt into README.md, and to the `prompts.csv` file. If your prompt includes quotes, you will need to double-quote them to escape in CSV file.

If the prompt is generated by ChatGPT, please add `<mark>Generated by ChatGPT</mark>` to the end of the contribution line.

## Description
copilot:summary

e.g.
```csv
"Hello","Say ""Hi"""
```

- [X] I've confirmed the prompt works well
- [X] I've added `Contributed by: [@yourusername](https://github.com/yourusername)`
- [X] I've added to the README.md
- [X] I've added to the `prompts.csv`
  - [X] Escaped quotes by double-quoting them
  - [X] No spaces after commas after double quotes. e.g. `"Hello","hi"`, not `"Hello", "hi"`
  - [X] Removed "Act as" from the title on CSV

Please make sure you've completed all the checklist.

### CODE REVIEW

**Comment by casch-at** [comment]
Whoops, duplicate of #758

**Comment by Blvdkk** [comment]
Help

**Comment by Blvdkk** [comment]
Hi

**Review by lozanopo — APPROVED** [review]

**Review by Blvdkk — APPROVED** [review]

**Comment by demoncoder-crypto** [comment]
Hello, is this resolved?

**Comment by casch-at** [comment]
> Hello, is this resolved?

Yes, closing it!

**Pull request closed without merging**
