### PR TITLE
Add "Act as a Chess Player"

### PR DESCRIPTION
**Pull request by orcuntuna**

### CODE REVIEW

**Comment by f** [comment]
@orcuntuna can you also add to prompts.csv

**Comment by orcuntuna** [comment]
@f I already added

**Comment by f** [comment]
Ups missed that

**Comment by gerrywastaken** [comment]
@orcuntuna That is pretty nuts... does it actually work?

**Comment by orcuntuna** [comment]
> @orcuntuna That is pretty nuts... does it actually work?

Yeah, It's playing with me but it needs to improve itself a little more. Sometimes it makes silly moves. It apologizes when I tell  it can't make this move :D

image

**Comment by gerrywastaken** [comment]
That is pretty shocking, did you finish a game with it?

**Pull request merged**
