### PR TITLE
Fix top banner

### PR DESCRIPTION
**Pull request by alien2003**
Adjust the top banner to accurately reflect the current situation in the Gaza conflict.

### CODE REVIEW

**Comment by u1dm** [comment]
and counting the murders on the Palistinians

**Review by victorabarros — APPROVED** [review]

**Comment by victorabarros** [comment]
@alien2003 
Thanks for that

**Review by nitzo — APPROVED** [review]

**Comment by RGdevz** [comment]
LGTM 👍

**Review by hoomb — APPROVED** [review]

**Comment by maxhr** [comment]
Please report to GitHub the owner of this repo - https://support.github.com/contact/report-abuse?category=report-abuse

**Pull request closed without merging**
